#+title: Usage

* Summary

This library works by resolving a few key directories and saving the results to
variables, namely:
+ Data, =DATA_HOME= and =DATA_DIRS=
+ Config, with =CONFIG_HOME= and =CONFIG_DIRS=
+ Executables, with =BIN_HOME=
+ State data, with =STATE_HOME=
+ Cached data, with =CACHE_HOME=
+ Runtime data, with =RUNTIME_DIR=

While it is possible to use these variables directly, it is recommended that you
make use of the accessor functions instead, which all follow this pattern:

#+begin_src julia
accessor() # Give the base directory(ies)
accessor(parts...) # Give the base directory(ies) joined with parts
accessor(proj::Project) # Give the base directory(ies) for proj
acessors(proj::Project, parts...) # proj directory(ies) joined with parts
#+end_src

Where ~accessor~ is a stand-in for the particular named directory being resolved.
Two boolean keyword arguments are often supported:
+ =create=, to create the path when it does not exist. This is different to simply
  piping the returned path into ~mkpath~ in that it:
  a. Takes care to create the base directory with the appropriate mode (=700=)
  b. Creates the directory component of the path with the default mode (usually =755=)
  c. If the path is to a file (i.e. the path does not end with =/=), ~touch~​es the file.
+ =existent=, to filter the list of provided paths to ones that exist (when applicable)

To give appropriate project-specific directories we can use a =XDG.Project=:

#+begin_src @docs
XDG.Project
#+end_src

The user and system forms of the various accessor functions are split into the
 =User= and =System= modules, with combined accessors in the =XDG= namespace.
 This essentially creates a tree of accessor functions:

+ User
  - ~data~
  - ~config~
    - ~bin~
  - ~state~
  - ~cache~
  - ~runtime~
  - ~fonts~
  - ~applications~
+ System
  - ~data~
  - ~config~
  - ~fonts~
  - ~applications~
+ ~data~
+ ~config~
+ ~fonts~
+ ~applications~

The =User= submodule also provides a number of other "user folder" accessors, namely:
+ ~desktop~
+ ~downloads~
+ ~documents~
+ ~music~
+ ~pictures~
+ ~videos~
+ ~templates~
+ ~public~

* Example usage

#+begin_src julia-repl
julia> using XDG

julia> XDG.CONFIG_HOME[]
"/home/tec/.config"

julia> XDG.User.config()
"/home/tec/.config"

julia> XDG.User.config("sub", "dir/")
"/home/tec/.config/sub/dir/"

julia> XDG.User.config(XDG.Project("mything"), "config.conf", create=true)
"/home/tec/.config/mything/config.conf"
#+end_src

* Variables

** Base directories

#+begin_src @docs
XDG.DATA_HOME
#+end_src

#+begin_src @docs
XDG.DATA_DIRS
#+end_src

#+begin_src @docs
XDG.CONFIG_HOME
#+end_src

#+begin_src @docs
XDG.CONFIG_DIRS
#+end_src

#+begin_src @docs
XDG.BIN_HOME
#+end_src

#+begin_src @docs
XDG.STATE_HOME
#+end_src

#+begin_src @docs
XDG.CACHE_HOME
#+end_src

#+begin_src @docs
XDG.RUNTIME_DIR
#+end_src

** User directories

#+begin_src @docs
XDG.DESKTOP_DIR
#+end_src

#+begin_src @docs
XDG.DOWNLOAD_DIR
#+end_src

#+begin_src @docs
XDG.DOCUMENTS_DIR
#+end_src

#+begin_src @docs
XDG.PICTURES_DIR
#+end_src

#+begin_src @docs
XDG.VIDEOS_DIR
#+end_src

#+begin_src @docs
XDG.TEMPLATES_DIR
#+end_src

#+begin_src @docs
XDG.PUBLICSHARE_DIR
#+end_src

** Other directories

#+begin_src @docs
XDG.APPLICATIONS_DIRS
#+end_src

#+begin_src @docs
XDG.FONTS_DIRS
#+end_src

* Functions

** User

#+begin_src @docs
XDG.User
#+end_src

#+begin_src @docs
XDG.User.data
#+end_src

#+begin_src @docs
XDG.User.config
#+end_src

#+begin_src @docs
XDG.User.bin
#+end_src

#+begin_src @docs
XDG.User.state
#+end_src

#+begin_src @docs
XDG.User.cache
#+end_src

#+begin_src @docs
XDG.User.runtime
#+end_src

-----

#+begin_src @docs
XDG.User.desktop
#+end_src

#+begin_src @docs
XDG.User.downloads
#+end_src

#+begin_src @docs
XDG.User.documents
#+end_src

#+begin_src @docs
XDG.User.music
#+end_src

#+begin_src @docs
XDG.User.pictures
#+end_src

#+begin_src @docs
XDG.User.videos
#+end_src

#+begin_src @docs
XDG.User.templates
#+end_src

#+begin_src @docs
XDG.User.public
#+end_src

-----

#+begin_src @docs
XDG.User.fonts
#+end_src

#+begin_src @docs
XDG.User.applications
#+end_src

** System

#+begin_src @docs
XDG.System
#+end_src

#+begin_src @docs
XDG.System.data
#+end_src

#+begin_src @docs
XDG.System.config
#+end_src

#+begin_src @docs
XDG.System.fonts
#+end_src

#+begin_src @docs
XDG.System.applications
#+end_src

** Combined

#+begin_src @docs
XDG.data
#+end_src

#+begin_src @docs
XDG.config
#+end_src

#+begin_src @docs
XDG.fonts
#+end_src

#+begin_src @docs
XDG.applications
#+end_src
